<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var $block \Magefan\Community\Block\JsScript
 * @var $mfSecureRenderer \Magefan\Community\Api\SecureHtmlRendererInterface
 */
?>
<?php $script = "
    window.MagefanJs = window.MagefanJs || {};

    window.MagefanJs.requestOptionsModifier = function (options) {
        if (options && options.url && !options.magefan_php_cookie_resp) {
            options.url += (options.url.indexOf('?') === -1 ? '?' : '&') + 'magefan_no_php_cookie_resp=1';
        }
        return options;
    };

    window.MagefanJs.ajax = function(options) {
        options = window.MagefanJs.requestOptionsModifier(options);
        var xmlhttp = new XMLHttpRequest();
        xmlhttp.onreadystatechange = function () {
            if (xmlhttp.readyState == XMLHttpRequest.DONE && xmlhttp.status == 200) {
                var data = xmlhttp.responseText;
                if (options.success) options.success(data);
            }
        };

        xmlhttp.open(options.type, options.url, true);

        var requestHeader = Object.assign({}, {
            'X-Requested-With': 'XMLHttpRequest',
            'Content-type': 'application/x-www-form-urlencoded'
        }, options.requestHeader ? options.requestHeader : {});

        for (var header in requestHeader) {
            xmlhttp.setRequestHeader(header, requestHeader[header]);
        }
        xmlhttp.send(options.data);
    };
"; ?>
<?= /* @noEscape */ $mfSecureRenderer->renderTag('script', $block->getScriptAttributes() ?: [], $script, false) ?>
