<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var $block \Magefan\Community\Block\JsScript
 * @var $mfSecureRenderer \Magefan\Community\Api\SecureHtmlRendererInterface
 */
?>
<?php $script = "
    window.MagefanJs = window.MagefanJs || {};
    window.MagefanJs.getCookie = function(cookieName) {
        let name = cookieName + '=';
        let decodedCookie = decodeURIComponent(document.cookie);
        let ca = decodedCookie.split(';');
        for(let i = 0; i <ca.length; i++) {
            let c = ca[i];
            while (c.charAt(0) === ' ') {
                c = c.substring(1);
            };
            if (c.indexOf(name) === 0) {
                return c.substring(name.length, c.length);
            }
        };
        return '';
    };
"; ?>
<?= /* @noEscape */ $mfSecureRenderer->renderTag('script', [], $script, false) ?>
