<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var $block \Magefan\Community\Block\JsScript
 * @var $mfSecureRenderer \Magefan\Community\Api\SecureHtmlRendererInterface
 */
?>
<?php $script = "
    window.MagefanJs = window.MagefanJs || {};
    window.MagefanJs.setCookie = function(name, value, params) {
        if (!name) {
            return;
        }

        params = params || {};
        
        var expires = params.expires;
        var path = params.path || '/';

        var cookieString = encodeURIComponent(name) + '=' + encodeURIComponent(value);

        if (expires instanceof Date) {
            cookieString += '; expires=' + expires.toUTCString();
        }
        cookieString += '; path=' + path;
        if (params.domain) {
            cookieString += '; domain=' + params.domain;
        }
        document.cookie = cookieString;
    };
"; ?>
<?= /* @noEscape */ $mfSecureRenderer->renderTag('script', [], $script, false) ?>
