<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * @var $block \Magefan\Community\Block\Adminhtml\HyvaThemeChecker
 */
?>
<?php if ($items = $block->getWitchModuleIsInstalled()) { ?>
    <div class="messages">
        <div class="message message-notice notice">
            <div data-ui-id="messages-message-notice" class="linv">
                <?= $block->escapeHtml(__('It looks like you are using the Hyva theme, ' .
                    'but the Hyva Magefan extensions for Hyva compatibility are not installed. ' .
                    'Please install these packages for the proper functioning of the modules on the Hyva theme. Run the CLI commands:')) ?>
                <div>
                    <?php
                        $commands = '';
                        foreach ($items as $name => $packageName) {
                            $commands .= 'composer require hyva-themes/magento2-compat-module-fallback' . PHP_EOL;
                            $commands .= 'composer require ' . $block->escapeHtml($packageName) . PHP_EOL;
                            $commands .= 'bin/magento setup:upgrade' . PHP_EOL;
                            $commands .= 'bin/magento setup:di:compile' . PHP_EOL;
                            $commands .= 'bin/magento setup:static-content:deploy' . PHP_EOL;
                        }
                    ?>
                    <pre><?=  /* @noEscape */  $commands ?>
                </div>
            </div>
        </div>
    </div>
<?php } ?>
