<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * Help template
 *
 * @var $block \Magefan\Community\Block\Adminhtml\Linv
 */
$items = $block->getItems();
$messages = $block->getMessages();
?>
<?php if ($items) { ?>
        <div class="messages">
            <div class="message message-notice notice" style="margin: 20px 3rem;">
                <div data-ui-id="messages-message-notice" class="linv">
                    <?= 'Important! So' . 'me ' . 'Mag'.'efan'.' Ex'.'tensions'.' a'.'re'.' dis'.'abl'.'ed d'.'ue '.'to i'.'nva'.'lid'.' Product K'.'ey: ' ?>
                    <div style="margin-left: 30px">
                        <br/>
                        <ul>
                            <?php foreach ($items as $key => $name) { ?>
                                <li>
                                    <?= $block->escapeHtml($result = preg_replace('/([A-Z])/', ' $1', $name)); ?>
                                    <?php if (isset($messages[$name])) { ?>
                                         - "<?= $block->escapeHtml($messages[$name]) ?>"
                                        <?php unset($messages[$name]) ?>
                                    <?php } ?>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                    <?= 'Ple' . 'ase che' . 'ck exten' . 'sions config' . 'uration' ?>.
                </div>
            </div>
        </div>
<?php } ?>


<?php if ($messages) { ?>
    <div class="messages">
        <?php foreach ($messages as $name => $message) { ?>
            <div class="message message-notice notice" style="margin: 20px 3rem;">
                <div data-ui-id="messages-message-notice" class="linv">
                    <?= 'Important! ' . 'Mag'.'efan'.' '. $block->escapeHtml( preg_replace('/([A-Z])/', ' $1', $name)) .': ' .$block->escapeQuote($message) ?>
                </div>
            </div>
        <?php } ?>
    </div>
<?php } ?>