<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * Help template
 *
 * @var $block \Magefan\Community\Block\Adminhtml\Linv
 * @var $escaper \Magento\Framework\Escaper
 */
$disabledItems = $block->getItems();
$messages = $block->getMessages();

if (!isset($escaper)) {
    /* Compatability fix for old Magento versions */
    $escaper = $block;
}
?>
<?php if ($disabledItems || $messages) { ?>
        <div class="messages">
            <div class="message message-notice notice" style="margin: 20px 3rem;">
                <div data-ui-id="messages-message-notice" class="linv">
                    <?= 'Important!' ?>
                    <div style="margin-left: 30px">
                        <br/>
                        <ul>
                            <?php foreach ($disabledItems as $key => $name) { ?>
                                <?php
                                    $result = preg_replace('/([A-Z])/', ' $1', $name)
                                ?>
                                <li>
                                    Mag<span></span>efan
                                    <?= $escaper->escapeHtml($result); ?>:
                                    <?php if (isset($messages[$name])) { ?>
                                        <?= $escaper->escapeHtml($messages[$name]) ?>
                                        <?php unset($messages[$name]) ?>
                                    <?php } else { ?>
                                        <?= ' dis'.'abl'.'ed d'.'ue '.'to i'.'nva'.'lid'.' Product K'.'ey.' ?>
                                    <?php } ?>
                                </li>
                            <?php } ?>
                            <?php foreach ($messages as $name => $message) { ?>
                                <li>
                                    <?= 'Mag'.'efan'.' '. $escaper->escapeHtml(
                                        preg_replace('/([A-Z])/', ' $1', $name)
                                    ) .': ' .$escaper->escapeQuote($message) ?>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                    <?= 'Ple' . 'ase che' . 'ck exten' . 'sion(s) config' . 'uration' ?>.
                </div>
            </div>
        </div>
<?php } ?>
