<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var \Magefan\Community\Block\Adminhtml\System\Config\Tabs $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php
if (!isset($escaper)) {
    /* Compatability fix for old Magento versions */
    $escaper = $block;
}
?>

<!-- ko scope: 'magefan_menu_config' -->
<!-- ko template: getTemplate() --><!-- /ko -->
<!-- /ko-->

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "magefan_menu_config": {
                    "component": "Magefan_Community/js/magefan-menu-config",
                    "config": <?= /* @noEscape */ json_encode($block->getConfigData()) ?>
                }
            }
        }
    }
}
</script>
