<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>

<?php
/**
 * @var $mfSecureRenderer \Magefan\Community\Api\SecureHtmlRendererInterface
 */
?>

<?php
$script ="
    document.addEventListener('DOMContentLoaded', loadMagefanMenu);

    function loadMagefanMenu()
    {
        var scriptUrl = '" . $block->getViewFileUrl("Magefan_Community::js/magefan-menu.js") . "';
        var script = document.createElement('script');
        script.src = scriptUrl;
        script.type = 'text/javascript';
        script.async = true;

        script.onload = function() {
            MagefanMenuManager.init();
        };

        script.onerror = function() {
            console.error('Failed to load the script: ' + scriptUrl);
        };

        document.head.appendChild(script);
    }"; ?>

<?= /* @noEscape */ $mfSecureRenderer->renderTag('script', [], $script, false) ?>
