<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * Help template
 *
 * @var $block \Magefan\Community\Block\Adminhtml\MfPartner
 */
?>
<div class="partners-block">
    <div class="mf partner" style="margin-bottom: 4rem; padding: 0 2.5rem; width: 33.33333333%;">
        <a href="https://magefan.com/" title="" target="_blank">
            <img
                class="mf-partner-image"
                src="<?= $block->getViewFileUrl('Magefan_Community::images/magefan-logo.svg') ?>"
                alt="Magefan" style="margin-bottom: 2.2rem;" />
        </a>
        <h3 class="partner-title"><?=__('Magento 2 Extensions')?></h3>
        <p class="partner-description">
            <?= __('Magefan is an eCommerce agency founded in October 2015. We believe product quality goes hand in hand with top-notch customer service.
We take both these aspects seriously when developing our solutions and providing services. That’s why Magefan company is about high-quality e-commerce solutions you can trust.
Our Magento 2 extensions have been downloaded more than 1, 300,000 times in recent years. Some of them you can get free of charge at our GitHub.
            ') ?>
            <br />
            <a href="https://magefan.com/magento-2-extensions" target="_blank">
                <?= __('Read More') ?>
            </a>
            <br />
            <a href="https://magefan.com/" target="_blank">
                <?= __('Partner Page') ?>
            </a>
        </p>
    </div>

</div>