<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * Help template
 *
 * @var $block \Magefan\Community\Block\Adminhtml\MfPartner
 */
?>
<div class="partners-block">
    <div class="partner">
        <a href="https://magefan.com/" title="" target="_blank">
            <img
                class="mf-partner-image"
                src="<?= $block->getViewFileUrl('Magefan_Community::images/magefan-logo.svg') ?>"
                alt="Magefan" style="margin-bottom: 2.2rem;" />
        </a>
        <h3 class="partner-title"><?=__('Magento 2 Extensions')?></h3>
        <p class="partner-description">
            <?= __('description description description description description description 
        description description description description description description description description description description description description '
            ) ?>
            <br />
            <a href="https://magefan.com/magento-2-extensions" target="_blank">
                <?= __('Read More') ?>
            </a>
            <br />
            <a href="https://magefan.com/" target="_blank">
                <?= __('Partner Page') ?>
            </a>
        </p>
    </div>

</div>