<?php
$disabledModules = $block->getModulesLinv();
if (!empty($disabledModules)) {
    ?>
    <div id="messages">
        <div class="messages">
            <div class="message message-notice notice">
                <div data-ui-id="messages-message-notice" class="linv">
                    <?php echo 'Mag'.'efan'.' Mo'.'dul'.'es w'.'ere'.' Dis'.'abl'.'ed d'.'ue '.'to I'.'nva'.'lid'.' K'.'ey: ';
                        $count = count($disabledModules);
                        foreach ($disabledModules as $key => $moduleName) {
                            echo $result = preg_replace('/([A-Z])/', ' $1', $moduleName);
                            if ($key < $count - 1) {
                                echo ', ';
                            }
                        }
                    ?>
                </div>
            </div>
        </div>
    </div>
<?php } ?>
