<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>

<section class="page-partners">
    <h2 class="page-sub-title"><?= $block->escapeHtml(__('Extension Vendors')) ?></h2>
    <div data-role="vendors-block" class="vendors-block">
        <div class="vendor">
            <img class="partner-image" src="<?= $block->getImageUrl() ?>" alt="Magefan">
            <h3 class="vendor-title">Magefan</h3>
            <p class="vendor-description">
                Magefan is an eCommerce agency delivering top-notch solutions for various B2B businesses on Magento or Shopify. We help companies generate more revenue and reach their business goals faster.<br>
                <a href="<?= $block->getModuleUrl() ?>" target="_blank">
                    Vendor Page
                </a>
            </p>
        </div>
    </div>
</section>
