<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>

<section class="page-partners">
    <h2 class="page-sub-title"><?= $block->escapeHtml(__('Extension Vendors')) ?></h2>
    <div data-role="vendors-block" class="partner-block">
        <div class="partner">
            <img class="vendor-image" src="<?= $this->getViewFileUrl('Magefan_Community::images/Logo-2-1.svg') ?>" alt="Magefan">
            <h3 class="partner-title">Magefan</h3>
            <p class="partner-description">
                Magefan is an eCommerce agency delivering top-notch solutions for various B2B businesses on Magento 2. We help companies generate more revenue and reach their business goals faster.<br>
                <a href="<?= 'https://mage' . 'fan.com/' ?>" target="_blank">
                    Vendor Page
                </a>
            </p>
        </div>
    </div>
</section>

<style>
   .page-partners .vendor-image{
       margin-bottom:2.2rem;
       margin-top:0.8rem;
       max-height:14rem;
       min-width:30rem;
   }
</style>